// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/aetherlinkx/config.proto

package aetherlinkx

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public account identifier. It must be a canonical UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A 32-byte, independently generated secret encoded as Base64URL.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_aetherlinkx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type TurboConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Drop UDP datagrams whose extra queue/path delay exceeds this value. Zero
	// disables deadline drops.
	MaxDatagramAgeMs uint32 `protobuf:"varint,2,opt,name=max_datagram_age_ms,json=maxDatagramAgeMs,proto3" json:"max_datagram_age_ms,omitempty"`
	// Per-direction destination dictionary entries. Zero disables compression.
	DestinationCacheSize uint32 `protobuf:"varint,3,opt,name=destination_cache_size,json=destinationCacheSize,proto3" json:"destination_cache_size,omitempty"`
	// Maximum accepted UDP payload. Valid range: 512..32768.
	MaxUdpPayload uint32 `protobuf:"varint,4,opt,name=max_udp_payload,json=maxUdpPayload,proto3" json:"max_udp_payload,omitempty"`
	// Optional transport tuning. Explicit stream sockopts always win.
	TcpKeepAliveIdle     int32  `protobuf:"varint,5,opt,name=tcp_keep_alive_idle,json=tcpKeepAliveIdle,proto3" json:"tcp_keep_alive_idle,omitempty"`
	TcpKeepAliveInterval int32  `protobuf:"varint,6,opt,name=tcp_keep_alive_interval,json=tcpKeepAliveInterval,proto3" json:"tcp_keep_alive_interval,omitempty"`
	TcpUserTimeout       int32  `protobuf:"varint,7,opt,name=tcp_user_timeout,json=tcpUserTimeout,proto3" json:"tcp_user_timeout,omitempty"`
	Congestion           string `protobuf:"bytes,8,opt,name=congestion,proto3" json:"congestion,omitempty"`
	MultipathTcp         bool   `protobuf:"varint,9,opt,name=multipath_tcp,json=multipathTcp,proto3" json:"multipath_tcp,omitempty"`
	MuxConcurrency       int32  `protobuf:"varint,10,opt,name=mux_concurrency,json=muxConcurrency,proto3" json:"mux_concurrency,omitempty"`
	XudpConcurrency      int32  `protobuf:"varint,11,opt,name=xudp_concurrency,json=xudpConcurrency,proto3" json:"xudp_concurrency,omitempty"`
	XudpProxyUdp443      string `protobuf:"bytes,12,opt,name=xudp_proxy_udp443,json=xudpProxyUdp443,proto3" json:"xudp_proxy_udp443,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TurboConfig) Reset() {
	*x = TurboConfig{}
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurboConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurboConfig) ProtoMessage() {}

func (x *TurboConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurboConfig.ProtoReflect.Descriptor instead.
func (*TurboConfig) Descriptor() ([]byte, []int) {
	return file_proxy_aetherlinkx_config_proto_rawDescGZIP(), []int{1}
}

func (x *TurboConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TurboConfig) GetMaxDatagramAgeMs() uint32 {
	if x != nil {
		return x.MaxDatagramAgeMs
	}
	return 0
}

func (x *TurboConfig) GetDestinationCacheSize() uint32 {
	if x != nil {
		return x.DestinationCacheSize
	}
	return 0
}

func (x *TurboConfig) GetMaxUdpPayload() uint32 {
	if x != nil {
		return x.MaxUdpPayload
	}
	return 0
}

func (x *TurboConfig) GetTcpKeepAliveIdle() int32 {
	if x != nil {
		return x.TcpKeepAliveIdle
	}
	return 0
}

func (x *TurboConfig) GetTcpKeepAliveInterval() int32 {
	if x != nil {
		return x.TcpKeepAliveInterval
	}
	return 0
}

func (x *TurboConfig) GetTcpUserTimeout() int32 {
	if x != nil {
		return x.TcpUserTimeout
	}
	return 0
}

func (x *TurboConfig) GetCongestion() string {
	if x != nil {
		return x.Congestion
	}
	return ""
}

func (x *TurboConfig) GetMultipathTcp() bool {
	if x != nil {
		return x.MultipathTcp
	}
	return false
}

func (x *TurboConfig) GetMuxConcurrency() int32 {
	if x != nil {
		return x.MuxConcurrency
	}
	return 0
}

func (x *TurboConfig) GetXudpConcurrency() int32 {
	if x != nil {
		return x.XudpConcurrency
	}
	return 0
}

func (x *TurboConfig) GetXudpProxyUdp443() string {
	if x != nil {
		return x.XudpProxyUdp443
	}
	return ""
}

type SecurityConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// off, prefer or required. Uses the standardized X-Wing hybrid KEM
	// (X25519 + ML-KEM-768), not the obsolete Kyber draft identifier.
	PqMode string `protobuf:"bytes,1,opt,name=pq_mode,json=pqMode,proto3" json:"pq_mode,omitempty"`
	// Client-side X-Wing public key, 1216 bytes as Base64URL.
	XwingPublicKey string `protobuf:"bytes,2,opt,name=xwing_public_key,json=xwingPublicKey,proto3" json:"xwing_public_key,omitempty"`
	// Server-side X-Wing private seed, 32 bytes as Base64URL.
	XwingPrivateKey string `protobuf:"bytes,3,opt,name=xwing_private_key,json=xwingPrivateKey,proto3" json:"xwing_private_key,omitempty"`
	// Adds an authenticated ChaCha20-Poly1305 record layer inside TLS/REALITY.
	InnerAead     bool `protobuf:"varint,4,opt,name=inner_aead,json=innerAead,proto3" json:"inner_aead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityConfig) Reset() {
	*x = SecurityConfig{}
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityConfig) ProtoMessage() {}

func (x *SecurityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityConfig.ProtoReflect.Descriptor instead.
func (*SecurityConfig) Descriptor() ([]byte, []int) {
	return file_proxy_aetherlinkx_config_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityConfig) GetPqMode() string {
	if x != nil {
		return x.PqMode
	}
	return ""
}

func (x *SecurityConfig) GetXwingPublicKey() string {
	if x != nil {
		return x.XwingPublicKey
	}
	return ""
}

func (x *SecurityConfig) GetXwingPrivateKey() string {
	if x != nil {
		return x.XwingPrivateKey
	}
	return ""
}

func (x *SecurityConfig) GetInnerAead() bool {
	if x != nil {
		return x.InnerAead
	}
	return false
}

type StealthConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Enabled                   bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MinChunkSize              uint32                 `protobuf:"varint,2,opt,name=min_chunk_size,json=minChunkSize,proto3" json:"min_chunk_size,omitempty"`
	MaxChunkSize              uint32                 `protobuf:"varint,3,opt,name=max_chunk_size,json=maxChunkSize,proto3" json:"max_chunk_size,omitempty"`
	MaxPaddingBytes           uint32                 `protobuf:"varint,4,opt,name=max_padding_bytes,json=maxPaddingBytes,proto3" json:"max_padding_bytes,omitempty"`
	PaddingProbabilityPercent uint32                 `protobuf:"varint,5,opt,name=padding_probability_percent,json=paddingProbabilityPercent,proto3" json:"padding_probability_percent,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StealthConfig) Reset() {
	*x = StealthConfig{}
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StealthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StealthConfig) ProtoMessage() {}

func (x *StealthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StealthConfig.ProtoReflect.Descriptor instead.
func (*StealthConfig) Descriptor() ([]byte, []int) {
	return file_proxy_aetherlinkx_config_proto_rawDescGZIP(), []int{3}
}

func (x *StealthConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *StealthConfig) GetMinChunkSize() uint32 {
	if x != nil {
		return x.MinChunkSize
	}
	return 0
}

func (x *StealthConfig) GetMaxChunkSize() uint32 {
	if x != nil {
		return x.MaxChunkSize
	}
	return 0
}

func (x *StealthConfig) GetMaxPaddingBytes() uint32 {
	if x != nil {
		return x.MaxPaddingBytes
	}
	return 0
}

func (x *StealthConfig) GetPaddingProbabilityPercent() uint32 {
	if x != nil {
		return x.PaddingProbabilityPercent
	}
	return 0
}

type ClientConfig struct {
	state  protoimpl.MessageState   `protogen:"open.v1"`
	Server *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// Intended only for private/testing deployments. Public endpoints must use
	// TLS or REALITY at the Xray transport layer.
	AllowInsecureTransport bool            `protobuf:"varint,2,opt,name=allow_insecure_transport,json=allowInsecureTransport,proto3" json:"allow_insecure_transport,omitempty"`
	Turbo                  *TurboConfig    `protobuf:"bytes,3,opt,name=turbo,proto3" json:"turbo,omitempty"`
	Security               *SecurityConfig `protobuf:"bytes,4,opt,name=security,proto3" json:"security,omitempty"`
	Stealth                *StealthConfig  `protobuf:"bytes,5,opt,name=stealth,proto3" json:"stealth,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_aetherlinkx_config_proto_rawDescGZIP(), []int{4}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetAllowInsecureTransport() bool {
	if x != nil {
		return x.AllowInsecureTransport
	}
	return false
}

func (x *ClientConfig) GetTurbo() *TurboConfig {
	if x != nil {
		return x.Turbo
	}
	return nil
}

func (x *ClientConfig) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *ClientConfig) GetStealth() *StealthConfig {
	if x != nil {
		return x.Stealth
	}
	return nil
}

type ServerConfig struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Users                   []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	AllowInsecureTransport  bool                   `protobuf:"varint,2,opt,name=allow_insecure_transport,json=allowInsecureTransport,proto3" json:"allow_insecure_transport,omitempty"`
	HandshakeTimeoutSeconds uint32                 `protobuf:"varint,3,opt,name=handshake_timeout_seconds,json=handshakeTimeoutSeconds,proto3" json:"handshake_timeout_seconds,omitempty"`
	Turbo                   *TurboConfig           `protobuf:"bytes,4,opt,name=turbo,proto3" json:"turbo,omitempty"`
	Security                *SecurityConfig        `protobuf:"bytes,5,opt,name=security,proto3" json:"security,omitempty"`
	Stealth                 *StealthConfig         `protobuf:"bytes,6,opt,name=stealth,proto3" json:"stealth,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_aetherlinkx_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_aetherlinkx_config_proto_rawDescGZIP(), []int{5}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetAllowInsecureTransport() bool {
	if x != nil {
		return x.AllowInsecureTransport
	}
	return false
}

func (x *ServerConfig) GetHandshakeTimeoutSeconds() uint32 {
	if x != nil {
		return x.HandshakeTimeoutSeconds
	}
	return 0
}

func (x *ServerConfig) GetTurbo() *TurboConfig {
	if x != nil {
		return x.Turbo
	}
	return nil
}

func (x *ServerConfig) GetSecurity() *SecurityConfig {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *ServerConfig) GetStealth() *StealthConfig {
	if x != nil {
		return x.Stealth
	}
	return nil
}

var File_proxy_aetherlinkx_config_proto protoreflect.FileDescriptor

const file_proxy_aetherlinkx_config_proto_rawDesc = "" +
	"\n" +
	"\x1eproxy/aetherlinkx/config.proto\x12\x16xray.proxy.aetherlinkx\x1a\x1acommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\"1\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\x89\x04\n" +
	"\vTurboConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12-\n" +
	"\x13max_datagram_age_ms\x18\x02 \x01(\rR\x10maxDatagramAgeMs\x124\n" +
	"\x16destination_cache_size\x18\x03 \x01(\rR\x14destinationCacheSize\x12&\n" +
	"\x0fmax_udp_payload\x18\x04 \x01(\rR\rmaxUdpPayload\x12-\n" +
	"\x13tcp_keep_alive_idle\x18\x05 \x01(\x05R\x10tcpKeepAliveIdle\x125\n" +
	"\x17tcp_keep_alive_interval\x18\x06 \x01(\x05R\x14tcpKeepAliveInterval\x12(\n" +
	"\x10tcp_user_timeout\x18\a \x01(\x05R\x0etcpUserTimeout\x12\x1e\n" +
	"\n" +
	"congestion\x18\b \x01(\tR\n" +
	"congestion\x12#\n" +
	"\rmultipath_tcp\x18\t \x01(\bR\fmultipathTcp\x12'\n" +
	"\x0fmux_concurrency\x18\n" +
	" \x01(\x05R\x0emuxConcurrency\x12)\n" +
	"\x10xudp_concurrency\x18\v \x01(\x05R\x0fxudpConcurrency\x12*\n" +
	"\x11xudp_proxy_udp443\x18\f \x01(\tR\x0fxudpProxyUdp443\"\x9e\x01\n" +
	"\x0eSecurityConfig\x12\x17\n" +
	"\apq_mode\x18\x01 \x01(\tR\x06pqMode\x12(\n" +
	"\x10xwing_public_key\x18\x02 \x01(\tR\x0exwingPublicKey\x12*\n" +
	"\x11xwing_private_key\x18\x03 \x01(\tR\x0fxwingPrivateKey\x12\x1d\n" +
	"\n" +
	"inner_aead\x18\x04 \x01(\bR\tinnerAead\"\xe1\x01\n" +
	"\rStealthConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12$\n" +
	"\x0emin_chunk_size\x18\x02 \x01(\rR\fminChunkSize\x12$\n" +
	"\x0emax_chunk_size\x18\x03 \x01(\rR\fmaxChunkSize\x12*\n" +
	"\x11max_padding_bytes\x18\x04 \x01(\rR\x0fmaxPaddingBytes\x12>\n" +
	"\x1bpadding_probability_percent\x18\x05 \x01(\rR\x19paddingProbabilityPercent\"\xc6\x02\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06server\x128\n" +
	"\x18allow_insecure_transport\x18\x02 \x01(\bR\x16allowInsecureTransport\x129\n" +
	"\x05turbo\x18\x03 \x01(\v2#.xray.proxy.aetherlinkx.TurboConfigR\x05turbo\x12B\n" +
	"\bsecurity\x18\x04 \x01(\v2&.xray.proxy.aetherlinkx.SecurityConfigR\bsecurity\x12?\n" +
	"\astealth\x18\x05 \x01(\v2%.xray.proxy.aetherlinkx.StealthConfigR\astealth\"\xf6\x02\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x128\n" +
	"\x18allow_insecure_transport\x18\x02 \x01(\bR\x16allowInsecureTransport\x12:\n" +
	"\x19handshake_timeout_seconds\x18\x03 \x01(\rR\x17handshakeTimeoutSeconds\x129\n" +
	"\x05turbo\x18\x04 \x01(\v2#.xray.proxy.aetherlinkx.TurboConfigR\x05turbo\x12B\n" +
	"\bsecurity\x18\x05 \x01(\v2&.xray.proxy.aetherlinkx.SecurityConfigR\bsecurity\x12?\n" +
	"\astealth\x18\x06 \x01(\v2%.xray.proxy.aetherlinkx.StealthConfigR\astealthBd\n" +
	"\x1acom.xray.proxy.aetherlinkxP\x01Z+github.com/xtls/xray-core/proxy/aetherlinkx\xaa\x02\x16Xray.Proxy.AetherLinkXb\x06proto3"

var (
	file_proxy_aetherlinkx_config_proto_rawDescOnce sync.Once
	file_proxy_aetherlinkx_config_proto_rawDescData []byte
)

func file_proxy_aetherlinkx_config_proto_rawDescGZIP() []byte {
	file_proxy_aetherlinkx_config_proto_rawDescOnce.Do(func() {
		file_proxy_aetherlinkx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_aetherlinkx_config_proto_rawDesc), len(file_proxy_aetherlinkx_config_proto_rawDesc)))
	})
	return file_proxy_aetherlinkx_config_proto_rawDescData
}

var file_proxy_aetherlinkx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proxy_aetherlinkx_config_proto_goTypes = []any{
	(*Account)(nil),                 // 0: xray.proxy.aetherlinkx.Account
	(*TurboConfig)(nil),             // 1: xray.proxy.aetherlinkx.TurboConfig
	(*SecurityConfig)(nil),          // 2: xray.proxy.aetherlinkx.SecurityConfig
	(*StealthConfig)(nil),           // 3: xray.proxy.aetherlinkx.StealthConfig
	(*ClientConfig)(nil),            // 4: xray.proxy.aetherlinkx.ClientConfig
	(*ServerConfig)(nil),            // 5: xray.proxy.aetherlinkx.ServerConfig
	(*protocol.ServerEndpoint)(nil), // 6: xray.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 7: xray.common.protocol.User
}
var file_proxy_aetherlinkx_config_proto_depIdxs = []int32{
	6, // 0: xray.proxy.aetherlinkx.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	1, // 1: xray.proxy.aetherlinkx.ClientConfig.turbo:type_name -> xray.proxy.aetherlinkx.TurboConfig
	2, // 2: xray.proxy.aetherlinkx.ClientConfig.security:type_name -> xray.proxy.aetherlinkx.SecurityConfig
	3, // 3: xray.proxy.aetherlinkx.ClientConfig.stealth:type_name -> xray.proxy.aetherlinkx.StealthConfig
	7, // 4: xray.proxy.aetherlinkx.ServerConfig.users:type_name -> xray.common.protocol.User
	1, // 5: xray.proxy.aetherlinkx.ServerConfig.turbo:type_name -> xray.proxy.aetherlinkx.TurboConfig
	2, // 6: xray.proxy.aetherlinkx.ServerConfig.security:type_name -> xray.proxy.aetherlinkx.SecurityConfig
	3, // 7: xray.proxy.aetherlinkx.ServerConfig.stealth:type_name -> xray.proxy.aetherlinkx.StealthConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proxy_aetherlinkx_config_proto_init() }
func file_proxy_aetherlinkx_config_proto_init() {
	if File_proxy_aetherlinkx_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_aetherlinkx_config_proto_rawDesc), len(file_proxy_aetherlinkx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_aetherlinkx_config_proto_goTypes,
		DependencyIndexes: file_proxy_aetherlinkx_config_proto_depIdxs,
		MessageInfos:      file_proxy_aetherlinkx_config_proto_msgTypes,
	}.Build()
	File_proxy_aetherlinkx_config_proto = out.File
	file_proxy_aetherlinkx_config_proto_goTypes = nil
	file_proxy_aetherlinkx_config_proto_depIdxs = nil
}
